<form action="<?= App::config('url') ?>distribucija/promjena/<?= $e->sifra ?>" method="post">

  <label for="naziv">Naziv</label>
  <input type="text" name="naziv" id="naziv" value="<?= $e->naziv ?>">

  <label for="osoba">Osoba</label>
  <select name="osoba" id="osoba">
    <?php foreach ($osobao as $o) : ?>
      <option <?php if ($e->osoba == $s->sifra) {
                echo ' selected="selected"';
              }
              ?> value="<?= $s->sifra ?>"><?= $s->naziv ?></option>
    <?php endforeach; ?>
  </select>


  <?= $poruka ?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
      <a class="alert button expanded" href="<?= App::config('url') ?>distribucija">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>

</form>