<form method="post" action="<?= App::config('url') ?>proizvoddistribucija/promjena/<?= $e->sifra ?>">
    <h4 class="text-center">Distribucija</h4>


    <label>Naziv proizvoda
        <input type="text" name="naziv_proizvoda" value="<?= $e->naziv_proizvoda ?>" />
    </label>

    <label>Cijena proizvoda
        <input type="number" name="cijena_proizvoda" value="<?= $e->cijena_proizvoda ?>" />
    </label>


    <label>Proizvođač
        <input type="text" name="proizvodac" value="<?= $e->proizvodac ?>" />
    </label>



    <label>Mjesto
        <input type="text" name="mjesto" value="<?= $e->mjesto ?>" />
    </label>

    <label>Vrijeme
        <input type="date" name="vrijeme" value="<?= $e->vrijeme ?>" />
    </label>


    <label>Količina
        <input type="text" name="kolicina" value="<?= $e->kolicina ?>" />
    </label>


    <label>Proizvod
        <input type="text" name="proizvod" value="<?= $e->proizvod ?>" />
    </label>
    

    <label>Distribucija
        <input type="text" name="distribucija" value="<?= $e->distribucija ?>" />
    </label>







    <?= $poruka ?>

    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <a class="alert button expanded" href="<?= App::config('url') ?>proizvoddistribucija">Odustani</a>
        </div>
        <div class="large-6 cell">
            <input type="submit" class="button expanded" value="Spremi"></input>
        </div>
    </div>


</form>