<form method="post" action="<?= App::config('url') ?>osoba/brisanje/<?= $osoba->sifra ?>">
  <h4 class="text-center">Brisanje osobe</h4>
  <label>Ime
    <input type="text" name="ime" value="<?= $osoba->ime ?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime" value="<?= $osoba->prezime ?>" />
  </label>

  <label>Mjesto Stanovanja
    <input type="text" name="mjesto_stanovanja" value="<?= $osoba->mjesto_stanovanja ?>" />
  </label>

  <label>Oib
    <input type="number" name="oib" value="<?= $osoba->oib ?>" />
  </label>

  <label>Datum Rođenja
    <input type="number" name="datum_rođenja" value="<?= $osoba->oib ?>" />
  </label>

  <label>Naziv Terena
    <input type="text" name="naziv_terena" value="<?= $osoba->naziv_terena ?>" />
  </label>

  <label>Smjena
    <input type="text" name="smjena" value="<?= $osoba->smjena ?>" />
  </label>

  <label>Email
    <input type="text" name="email" value="<?= $osoba->email ?>" />
  </label>

  <?= $poruka ?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
      <a class="alert button expanded" href="<?= App::config('url') ?>osoba">Odustani</a>
    </div>
    <div class="large-6 cell">
      <?php if ($brisanje) : ?>
        <input type="hidden" name="obrisi" value="true" />
        <input type="submit" class="button expanded" value="Obriši"></input>
      <?php else : ?>
        osoba 
      <?php endif; ?>
    </div>
  </div>


</form>