<a href="<?= App::config('url') ?>osoba/novi" class="success button expanded">Dodaj novi</a>

<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Mjesto Stanovanja</th>
            <th>Oib</th>
            <th>Datum Rođenja</th>
            <th>Naziv Terena</th>
            <th>Smjena</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($osoba as $o) : ?>
            <tr>
                <td><?= $o->ime ?></td>
                <td><?= $o->prezime ?></td>
                <td><?= $o->mjesto_stanovanja ?></td>
                <td><?= $o->oib ?></td>
                <td><?= $o->datum_rodenja ?></td>
                <td><?= $o->naziv_terena ?></td>
                <td><?= $o->smjena ?></td>
                <td><?= $o->email ?></td>
                <td>
                    <a href="<?= App::config('url') ?>osoba/promjena/<?= $o->sifra ?>">
                        <i style="color: blue;" class="step fi-pencil size-36"></i>
                    </a>
                
                    <a href="<?= App::config('url') ?>osoba/brisanje/<?= $o->sifra ?>">
                        <i style="color: red;" class="step fi-page-delete size-36"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

