<form method="post" action="<?= App::config('url') ?>poslovnica/promjena/<?= $e->sifra ?>">
    <h4 class="text-center">Informacije o poslovnicama</h4>
    <label>Naziv
        <input type="text" name="naziv" value="<?= $e->naziv ?>" />
    </label>

    <label>Mjesto
        <input type="text" name="mjesto" value="<?= $e->mjesto ?>" />
    </label>

    <label>Email
        <input type="text" name="email" value="<?= $e->email ?>" />
    </label>



    </label>
    <?= $poruka ?>

    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <a class="alert button expanded" href="<?= App::config('url') ?>poslovnica">Odustani</a>
        </div>
        <div class="large-6 cell">
            <input type="submit" class="button expanded" value="Promjeni"></input>
        </div>

    </div>


</form>