<a href="<?= App::config('url') ?>poslovnica/novi" class="button expanded">Dodaj novu Poslovnicu</a>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Mjesto</th>
            <th>Email stanovanja</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($entiteti as $e) : ?>
            <tr>
                <td><?= $e->naziv ?></td>
                <td><?= $e->mjesto ?></td>
                <td><?= $e->email ?></td>
                <td>
                    <a href="<?= App::config('url') ?>poslovnica/promjena/<?= $e->sifra ?>">
                        <i style="color: blue;"  class="step fi-pencil size-36"></i>
                    </a>

                    <a href="<?= App::config('url') ?>poslovnica/brisanje/<?= $e->sifra ?>">
                        <i style="color: red;" class="step fi-page-delete size-36"></i>
                    </a>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>