<form method="post" action="<?= App::config('url') ?>distribucija/promjena/<?= $e->sifra ?>">
    <h4 class="text-center">Distribucija</h4>


    <label>Mjesto
        <input type="text" name="mjesto" value="<?= $e->mjesto ?>" />
    </label>

    <label>Vrijeme
        <input type="text" name="vrijeme" value="<?= $e->vrijeme ?>" />
    </label>


    <label>Količina
        <input type="email" name="kolicina" value="<?= $e->kolicina ?>" />
    </label>

    <label>Količina
        <input type="email" name="kolicina" value="<?= $e->kolicina ?>" />
    </label>


    <?= $poruka ?>

    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <a class="alert button expanded" href="<?= App::config('url') ?>distribucija">Odustani</a>
        </div>
        <div class="large-6 cell">
            <input type="submit" class="button expanded" value="Spremi"></input>
        </div>
    </div>


</form>