<a href="<?= App::config('url') ?>distribucija/nova" class=" button expanded">Dodaj novu distribuciju</a>

<table>
    <thead>
        <tr>
            <th>Ime </th>
            <th>Prezime </th>
            <th>Mjesto Stanovanja</th>
            <th>Oib</th>
            <th>Naziv terena</th>
            <th>Smjena</th>
            <th>Email </th>
            <th>Mjesto </th>
            <th>Vrijeme</th>
            <th>Količina</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($entiteti as $e) : ?>
            <tr>
                <td><?= $e->ime?></td>
                <td><?= $e->prezime?></td>
                <td><?= $e->mjesto_stanovanja ?></td>
                <td><?= $e->oib ?></td>
                <td><?= $e->naziv_terena ?></td>
                <td><?= $e->smjena ?></td>
                <td><?= $e->email ?></td>
                <td><?= $e->mjesto ?></td>
                <td><?= $e->vrijeme ?></td>
                <td><?= $e->kolicina ?></td>
                <td><a href="<?= App::config('url') ?>distribucija/promjena/<?= $e->sifra ?>">Promjena</a>
                    &nbsp;&nbsp;<a href="<?= App::config('url') ?>distribucija/brisanje/<?= $e->sifra ?>" onclick="return confirm('Sigurno želite obrisati distribucija <?= $e->ime . ' ' . $e->prezime  ?>?');">Brisanje</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>