<a href="<?= App::config('url') ?>rezervacija/nova" class="success button expanded">Dodaj novu rezervaciju</a>

<table>
    <thead>
        <tr>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($entiteti as $e) : ?>
            <tr>
                <th>
                    
                </th>
                <!--         nastavak         -->
                <a href="<?= App::config('url') ?>osoba/promjena/<?= $e->sifra ?>">
                    <i style="color: blue;" class="step fi-pencil size-36"></i>
                </a>

                <a href="<?= App::config('url') ?>osoba/brisanje/<?= $e->sifra ?>">
                    <i style="color: red;" class="step fi-page-delete size-36"></i>
                </a>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>