<a href="<?= App::config('url') ?>distribucija/novi" class="success button expanded">Dodaj novu distribuciju</a>

<table>
    <thead>
        <tr>
            <th>Mjesto</th>
            <th>Vrijeme</th>
            <th>Količina</th>
            <th>Osoba</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($entiteti as $e) : ?>
            <tr>
                <td><?= $e->mjesto ?></td>
                <td><?= $e->vrijeme ?></td>
                <td><?= $e->kolicina ?></td>
                <td><?= $e->osoba ?></td>
                <td>
                    <a href="<?= App::config('url') ?>distribucija/promjena/<?= $e->sifra ?>">
                        <i style="color: blue;" class="step fi-pencil size-36"></i>
                    </a>

                    <a href="<?= App::config('url') ?>distribucija/brisanje/<?= $e->sifra ?>">
                        <i style="color: red;" class="step fi-page-delete size-36"></i>
                    </a>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>